schemas.py

from pydantic import BaseModel
from typing import Optional

class ProposalRequest(BaseModel):
    job_description: str
    client_name: Optional[str] = None

class ChatRequest(BaseModel):
    message: Optional[str] = None           # No longer required for the first call
    job_description: Optional[str] = None   # No longer required for follow-ups
    thread_id: Optional[str] = None         # Generated by backend if missing